### ISSUE TITLE
Build failure reasons not reported since update 

### ISSUE THREAD

**Issue by con242** [dxatscale/sfpowerscripts#1177]
**Describe the bug**
If a package fails during build, previously the error description was printed in the build log. Since Nov22 release, output seems to be formatted, but errors are displayed as "undefined". 

Expected: 
```
{
  "status": 1,
  "name": "",
  "message": "Case.FormulaName__c: Syntax error. Extra ')'",
  "exitCode": 1,
  "context": "PackageVersionCreateCommand",
  "stack": "Case.FormulaName__c: Syntax error. Extra ')'\n    at Function.wrap (/usr/local/sfdx/node_modules/@salesforce/core/lib/sfError.js:61:25)\n    at PackageVersionCreateCommand.catch (/usr/local/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:255:44)\n    at async PackageVersionCreateCommand._run (/usr/local/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:106:13)\n    at async Config.runCommand (/usr/local/sfdx/node_modules/@oclif/core/lib/config/config.js:272:25)\n    at async run (/usr/local/sfdx/node_modules/@oclif/core/lib/main.js:76:5)\nCaused by: Error: Case.FormulaName__c: Syntax error. Extra ')'\n    at /usr/local/sfdx/node_modules/salesforce-alm/dist/lib/package/packageUtils.js:712:27\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "warnings": [],
  "commandName": "PackageVersionCreateCommand"
}
Removed all childs of PACKAGENAME from queue
```

Actual: 
```
Package creation for PACKAGENAME Initiated
Status: Initializing, Next Status check in 30 seconds
Status: VerifyingFeaturesAndSettings, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds

Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingMetadata, Next Status check in 30 seconds
Status: Error, Next Status check in 30 seconds
Unable to create  PACKAGENAME due to 
Creation errors: 
1) undefined
Removed all childs of PACKAGENAME from queue
```

**To Reproduce**
create any build error with a single error message. It might be, that error responses are not correctly handled if single element is returned instead of array. 

**Platform Details (please complete the following information):**
 - OS: Gitlab CI 
 - Version:20.2.4 -Release:November 22
 - Salesforce CLI Version: 7.170 
 - CI Platform: Gitlab

**Comment by azlam-abdulsalam** [comment]
@con242  ~this looks like a limitation with the current packaging lib , I  will confirm~ wrong api usage. fix on the way!
