### ISSUE TITLE
Source packages failing to install on v51 of the SFDX CLI

### ISSUE THREAD

**Issue by aly76** [dxatscale/sfpowerscripts#398]
**Describe the bug**
Release v51 of the SFDX CLI uses REST API by default for mdapi depoyments, and this is causing JSON parser errors.

<https://github.com/forcedotcom/cli/issues/870>
**To Reproduce**
Run any of the commands that utilise mdapi deployment e.g. `sfpowerscripts:orchestrator:deploy`, Install Source Package 

**Expected behavior**
The deployment is queued successfully

**Screenshots**
```
{
  "status": 1,
  "name": "Error",
  "message": "JSON_PARSER_ERROR: Can not deserialize: unexpected array at [line:1, column:73]",
  "exitCode": 1,
  "commandName": "MdapiDeployCommand",
  "stack": "Error: JSON_PARSER_ERROR: Can not deserialize: unexpected array at [line:1, column:73]\n    at Request._callback (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/salesforce-alm/dist/lib/core/force.js:590:29)\n    at Request.self.callback (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:467:12)\n    at Request.<anonymous> (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:467:12)\n    at IncomingMessage.<anonymous> (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:421:28)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:467:12)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\nOuter stack:\n    at Function.wrap (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at MdapiDeployCommand.catch (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/salesforce-alm/dist/ToolbeltCommand.js:248:46)\n    at MdapiDeployCommand._run (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at Config.runCommand (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/@oclif/config/lib/config.js:173:24)\n    at Main.run (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/@oclif/command/lib/main.js:27:9)\n    at Main._run (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/node_modules/@oclif/command/lib/command.js:43:20)\n    at Object.run (/Users/alan.ly/.local/share/sfdx/client/7.88.4-3b2e55c3f1/dist/cli.js:121:21)",
  "warnings": []
}
```

**Platform Details (please complete the following information):**
 - OS: macOS Catalina Version 10.15.7
 - Version [e.g. CLI Version  eg: 1.6.6] 
 - Salesforce Version: Version 7.88.4
 - CI Platform: N/A

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Fixed in  https://github.com/Accenture/sfpowerscripts/releases/tag/Release_19.3
