### ISSUE TITLE
Quickbuild - "Invalid time value" - error

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerscripts#697]
### Discussed in https://github.com/Accenture/sfpowerscripts/discussions/696

<div type='discussions-op-text'>

<sup>Originally posted by **bjanderson70** September 21, 2021</sup>
**Problem Statement:**
I have a github action that fires when I check-in/commit. There appears to be an invalid time-value passed to _getFormattedTime_ in **GetFormattedTime.ts**

**_Suggestions_**? Short of putting a try/catch around the code ...I have not ventured into the sfdx cli to determine what cause this ... looking for some suggestions in the meantime? TIA

**Command:** - ran in a github action
_sfdx sfpowerscripts:orchestrator:quickbuild -v devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/} --json --waittime=60_

**Error Encountered:**

Run sfdx sfpowerscripts:orchestrator:quickbuild -v devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/} --json --waittime=60
 ›   Warning: sfdx-cli update available from 7.110.0 to 7.116.2.
-----------sfpowerscripts orchestrator ------------------
command: quickbuild
Build Packages Only Changed: true
Config File Path: config/project-scratch-def.json
Artifact Directory: artifacts
---------------------------------------------------------

Checking last known tags for cqrs-service to determine whether package is to be built...

Utilizing tag cqrs-service_v1.0.0.1251293990 for cqrs-service
Checking for changes in source directory src/utils/cqrs
Checking for changes to package descriptor in sfdx-project.json
Packages scheduled for build
┌─────────┬────────────────────┬────────────────┐
│ Package │ Reason to be built │ Last Known Tag │
└─────────┴────────────────────┴────────────────┘
No packages found to be built.. Exiting.. 
----------------------------------------------------------------------------------------------------
{
    **"status": 1,**
    "name": "RangeError",
    "message": "Invalid time value",
    "exitCode": 1,
    "commandName": "QuickBuild",
    "stack": "RangeError: Invalid time value\n    at Date.toISOString (<anonymous>)\n    at Object.getFormattedTime [as default] (/sfdx_plugins/.local/share/sfdx/node_modules/@dxatscale/sfpowerscripts/lib/utils/GetFormattedTime.js:6:27)\n    at QuickBuild.<anonymous> (/sfdx_plugins/.local/share/sfdx/node_modules/@dxatscale/sfpowerscripts/lib/BuildBase.js:89:171)\n    at Generator.next (<anonymous>)\n    at fulfilled (/sfdx_plugins/.local/share/sfdx/node_modules/@dxatscale/sfpowerscripts/lib/BuildBase.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\nOuter stack:\n    at Function.wrap (/sfdx_plugins/.local/share/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at QuickBuild.catch (/sfdx_plugins/.local/share/sfdx/node_modules/@dxatscale/sfpowerscripts/node_modules/@salesforce/command/lib/sfdxCommand.js:255:67)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async QuickBuild._run (/sfdx_plugins/.local/share/sfdx/node_modules/@dxatscale/sfpowerscripts/node_modules/@salesforce/command/lib/sfdxCommand.js:95:13)\n    at async Config.runCommand (/usr/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
    "warnings": []
}
Error: Process completed with exit code 1.
</div>

**Comment by azlam-abdulsalam** [comment]
Yes you are spot on!
